![Pyton_comic](https://biomedicalhub.github.io/python-data/images/python.png)

# Lab 1: Python Refresher and Autodiff

## Part 1: Manipulating data with Pandas
Before you do any statistics, you need to get data into the python environment. In this part you will learn how to 
 1. Load data from CSV files
 2. Subset data frames
 3. Edit data to make it easier to manage
 4. Merge multiple datasets
 
Pandas is a python module used to handle tabular data, in a format similar to R's data.frame data structure. We will be using it extensively throuhgout the semester. If pandas is not installed already, use `conda` to install it into your `Computational_methods` environment. For a quick reference of pandas methods, check out the [Pandas cheat sheet](https://pandas.pydata.org/Pandas_Cheat_Sheet.pdf). Google is also your friend here 😁

In [43]:
import os
print(os.__file__)
import pandas as pd
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

/anaconda3/lib/python3.7/os.py


### 1.1 Load CSV File

a. Use`pandas` to read `rhc.csv`. A description of this dataset is [here](http://biostat.mc.vanderbilt.edu/wiki/pub/Main/DataSets/rhc.html). 

In [3]:
rhc = pd.read_csv("rhc.csv")

b. View your new data frame, and get all of the feature names. 

In [4]:
rhc.columns.values

array(['Unnamed: 0', 'cat1', 'cat2', 'ca', 'sadmdte', 'dschdte', 'dthdte',
       'lstctdte', 'death', 'cardiohx', 'chfhx', 'dementhx', 'psychhx',
       'chrpulhx', 'renalhx', 'liverhx', 'gibledhx', 'malighx', 'immunhx',
       'transhx', 'amihx', 'age', 'sex', 'edu', 'surv2md1', 'das2d3pc',
       't3d30', 'dth30', 'aps1', 'scoma1', 'meanbp1', 'wblc1', 'hrt1',
       'resp1', 'temp1', 'pafi1', 'alb1', 'hema1', 'bili1', 'crea1',
       'sod1', 'pot1', 'paco21', 'ph1', 'swang1', 'wtkilo1', 'dnr1',
       'ninsclas', 'resp', 'card', 'neuro', 'gastr', 'renal', 'meta',
       'hema', 'seps', 'trauma', 'ortho', 'adld3p', 'urin1', 'race',
       'income', 'ptid'], dtype=object)

### 1.2 Structure
a. What are the dimensions of the data frame, and the classes of each column? Can you get a summary of every feature in the data? (Try the `describe` method)

In [5]:
rhc.describe()

Unnamed: 0       sadmdte       dschdte        dthdte      lstctdte  \
count  5735.000000   5735.000000   5734.000000   3722.000000   5735.000000   
mean   2868.000000  11638.686312  11660.050401  11753.869156  11781.257890   
std    1655.696228    513.967751    513.447322    538.812330    524.094168   
min       1.000000  10754.000000  10757.000000  10757.000000  10756.000000   
25%    1434.500000  11163.500000  11184.000000  11267.000000  11316.000000   
50%    2868.000000  11759.000000  11777.000000  11831.500000  11868.000000   
75%    4301.500000  12097.000000  12120.000000  12208.000000  12244.000000   
max    5735.000000  12441.000000  12560.000000  12783.000000  12644.000000   

          cardiohx        chfhx     dementhx      psychhx     chrpulhx  \
count  5735.000000  5735.000000  5735.000000  5735.000000  5735.000000   
mean      0.176635     0.178030     0.098344     0.067306     0.189887   
std       0.381393     0.382571     0.297805     0.250573     0.392246   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%       0.000000     0.000000     0.000000     0.000000     0.000000   
50%       0.000000     0.000000     0.000000     0.000000     0.000000   
75%       0.000000     0.000000     0.000000     0.000000     0.000000   
max       1.000000     1.000000     1.000000     1.000000     1.000000   

           ...             bili1        crea1         sod1         pot1  \
count      ...       5735.000000  5735.000000  5735.000000  5735.000000   
mean       ...          2.267067     2.133017   136.768963     4.066693   
std        ...          4.801538     2.053080     7.655160     1.028353   
min        ...          0.099991     0.099991   101.000000     1.099854   
25%        ...          0.799927     1.000000   132.000000     3.399902   
50%        ...          1.009766     1.500000   136.000000     3.799805   
75%        ...          1.399902     2.399902   142.000000     4.599609   
max        ...         58.195312    25.097656   178.000000    11.898438   

            paco21          ph1      wtkilo1       adld3p        urin1  \
count  5735.000000  5735.000000  5735.000000  1439.000000  2707.000000   
mean     38.748975     7.388413    67.827817     1.182071  2192.453665   
std      13.183445     0.109812    29.055534     1.819057  1525.140006   
min       1.000000     6.579102     0.000000     0.000000     0.000000   
25%      31.000000     7.339844    56.299990     0.000000  1110.000000   
50%      37.000000     7.399998    70.000000     0.000000  1927.000000   
75%      42.000000     7.459961    83.699950     2.000000  2955.000000   
max     156.000000     7.769531   244.000000     7.000000  9000.000000   

               ptid  
count   5735.000000  
mean    5134.006452  
std     2972.206379  
min        5.000000  
25%     2561.500000  
50%     5131.000000  
75%     7689.000000  
max    10278.000000  

[8 rows x 42 columns]

### 1.3 Subset
a. Select the first 10 columns of the data frame. (! Remember that that the first element of any list or vector in Python is indexed as 0 !)

In [45]:
rhc.iloc[:,0:10].head()

Unnamed: 0               cat1           cat2   ca  sadmdte  dschdte  \
0           1               COPD            NaN  Yes    11142  11151.0   
1           2      MOSF w/Sepsis            NaN   No    11799  11844.0   
2           3  MOSF w/Malignancy  MOSF w/Sepsis  Yes    12083  12143.0   
3           4                ARF            NaN   No    11146  11183.0   
4           5      MOSF w/Sepsis            NaN   No    12035  12037.0   

    dthdte  lstctdte death  cardiohx  
0      NaN     11382    No         0  
1  11844.0     11844   Yes         1  
2      NaN     12400    No         0  
3  11183.0     11182   Yes         0  
4  12037.0     12036   Yes         0

b. Select individuals between 10 and 25 years of age. How many such individuals are there?

In [7]:
rhc.loc[(rhc['age'] >= 10.0) & (rhc['age'] <= 25.0), :].shape

(145, 63)

c. Select rows that are not missing any missing data.

In [8]:
rhc.dropna().head()

Unnamed: 0               cat1           cat2          ca  sadmdte  \
110         111  MOSF w/Malignancy  MOSF w/Sepsis  Metastatic    12025   
168         169  MOSF w/Malignancy  MOSF w/Sepsis         Yes    12433   
249         250  MOSF w/Malignancy  MOSF w/Sepsis         Yes    12197   
362         363               COPD    Lung Cancer  Metastatic    12331   
416         417                ARF  MOSF w/Sepsis          No    12311   

     dschdte   dthdte  lstctdte death  cardiohx  ...   meta  hema  seps  \
110  12032.0  12075.0     12074   Yes         0  ...    Yes    No    No   
168  12440.0  12440.0     12440   Yes         0  ...     No    No   Yes   
249  12242.0  12332.0     12332   Yes         0  ...     No    No   Yes   
362  12335.0  12444.0     12444   Yes         0  ...     No    No    No   
416  12319.0  12362.0     12362   Yes         0  ...     No    No   Yes   

     trauma  ortho  adld3p   urin1   race      income  ptid  
110      No     No     1.0  2525.0  white  Under $11k   193  
168      No     No     0.0  3665.0  white    $11-$25k   292  
249      No     No     0.0  2915.0  white    $25-$50k   445  
362      No     No     0.0  2250.0  black  Under $11k   634  
416      No     No     5.0  1135.0  white  Under $11k   716  

[5 rows x 63 columns]

### 1.5 Editing

a. Add a `lengthstay` column with the difference between the study admission date `sadmdte` and the discharge date `dschdte`. The date is in a censored format to protect the identify of the individuals in the dataset. 

In [9]:
rhc['lengthstay'] = rhc['sadmdte'] - rhc['dschdte']

b. Normalize the values of a lab test of your choice. i.e. subtract the mean value and divide by the standard deviation. 

In [10]:
rhc['urin1_normalized'] = (rhc['urin1'] - rhc['urin1'].mean())/rhc['urin1'].std()

### 1.4 Merging

Load `rhc_1.csv` and `rhc_2.csv`. Select the first 10 columns of both tables, then combine them. Save the ouput as `rhc_new.csv`, and include this as part of your submission on Courseworks. 

In [11]:
rhc_1 = pd.read_csv("rhc_1.csv").iloc[:,0:10]
rhc_2 = pd.read_csv("rhc_2.csv").iloc[:,0:10]

rhc_new = rhc_1.append(rhc_2)
rhc_new.to_csv("rhc_new.csv")

## Part 2: Python Basics and Object Oriented Programming (OOP)
While data frames are a good way to manage data in the format it is give to you in, you may want to organize your data in a way that makes more sense from a computational standpoint. Fortunately, python has rich support for Object Oriented Programming. In Python, classes are types of objects. You can think of a class as a scaffold that will hold more data in a structured way. Classes can contain *attributes*, which describe the object, and *methods*, which perform some function on the object. 

This is an example of a class called `Patient`, which is initialized with an ID and age attribute. `Patient` also has a class attribute, which is the same for all instances. This is fine for us, but it you happen to be a veterinary informatician, you may want to change `species` to `'Felis catus'`. There is also a method which prints the patients ID and age. 

a. Add an attribute to `Patient` for their disease category, an attribute for one lab test value, and a method called `DieseaseDescription` which prints the patient's ID, disease, and lab test value, in some human readable format. 

In [12]:
class Patient:
    
    # Class Attribute
    species = 'Homo sapiens'
    
    # Initializer / Instance Attributes
    def __init__(self, ID, age, disease_cat, lab_test_1):
        self.ID = ID
        self.age = age
        self.disease_cat = disease_cat
        self.lab_test_1 = lab_test_1
        
    # Instance method
    def description(self):
        return "Patient #{} is {} years old".format(self.ID, self.age)
    
    def disease_description(self):
        return "Patient #{} has {} and recently had test values of {}".format(self.ID, self.disease_cat, self.lab_test_1)
    

In [13]:
# Example Patient
ex_pnt = Patient(9, 25, 'diabetes', 100)
print(ex_pnt.description())
print(ex_pnt.species)

Patient #9 is 25 years old
Homo sapiens


b. For the first 100 individuals in `rhc` with non-missing values for their disease and lab test you chose, initialize a `Patient` object for each, and save it in a list data structure. Then call the `DiseaseDescription` method for each object in the list. 

In [14]:
patient_list = []

counter = 0
for index,row in rhc.dropna().iloc[0:100,:].iterrows():
    counter += 1
    patient_list.append(Patient(counter, row['age'], row['cat1'], row['urin1_normalized']))
    
for patient in patient_list:
    print(patient.disease_description())

Patient #1 has MOSF w/Malignancy and recently had test values of 0.2180431529189412
Patient #2 has MOSF w/Malignancy and recently had test values of 0.9655155134034696
Patient #3 has MOSF w/Malignancy and recently had test values of 0.4737573815057535
Patient #4 has COPD and recently had test values of 0.03773183788977864
Patient #5 has ARF and recently had test values of -0.6933485848648259
Patient #6 has ARF and recently had test values of 0.6802957969027943
Patient #7 has MOSF w/Malignancy and recently had test values of -0.22453916578900326
Patient #8 has ARF and recently had test values of 1.7228230365259523
Patient #9 has MOSF w/Malignancy and recently had test values of 2.8243612519768364
Patient #10 has ARF and recently had test values of 0.24558160830521328
Patient #11 has ARF and recently had test values of -0.9011983552802606
Patient #12 has ARF and recently had test values of -1.4375425578033696
Patient #13 has MOSF w/Malignancy and recently had test values of -0.3294475672

## Part 3: Vectorized programming with pytorch
Let's turn up the heat a bit 🔥🔥🔥. A central focus of this course is learning neural network architecture, and PyTorch is one of the most common Python modules used for this task. If you haven't already, install it into your `Computational_methods` environment. More information on installing Pytorch is [here](https://pytorch.org/get-started/locally/). Do whatever instructions apply to your computer, but make sure you install PyTorch using conda, and that it installs into your environment. 

In [1]:
import torch
import numpy as np

### 3.1 Tensors
Primarily, Pytorch can be used as a replacement for Numpy, to take advantage of the parallel processing power of GPUs. Torch tensors are defined similarly to `np.array`s, so the syntax should be familiar if you have used Numpy before. Check out a cheat sheet for Pytorch [here](https://www.sznajdman.com/wp-content/uploads/2018/02/pytorch-cheat.jpg)

You can easily make random tensors of any dimensions. Use `torch.rand` to draw from a Uniform distribution between 0 and 1, and `torch.randn` to draw from a Gaussian with $\mu = 0$ and $\sigma = 1$. For this exercise, all matrix entries must be greater than 0, so draw random values from the appropriate distribution. 

a. Intialize a random 5 x 1 tensor called `T1` and print it. 

In [2]:
T1 = torch.randn(5,1)

b. Initialize a random 5 x 3 tensor called `T2`, and print it. 

In [3]:
T2 = torch.randn(5,3, requires_grad = True)

c. Initialize a random 5 x 3 x 2 tensor called `T3`, and print it. 

In [4]:
T3 = torch.randn(5,3,2)

### 3.2 Tensor Operations
Try some basic math operations (+, -, \*, / ) on your three new tensors. 

In [5]:
T2 - T1

tensor([[ 1.9141, -0.8521, -0.9750],
        [ 0.2767, -2.4254, -1.4106],
        [-0.9948, -0.6592, -1.9730],
        [ 2.3068, -0.1912,  3.1698],
        [-0.3291,  1.5397,  0.3168]], grad_fn=<SubBackward0>)

a. What is the difference between `T1 * T2`, `T1.t().mm(T2)`, and `T2.t().mm(T1)`?

In [6]:
T1*T2 # tensor product; produces a 5x3 tensor (which is the size of T2)

T1.t().mm(T2) # transpose of T1, then take the matrix-matrix product

T2.t().mm(T1) # transpose of T2, then take the matrix-matrix product

tensor([[ 1.0833],
        [ 0.6929],
        [-3.2816]], grad_fn=<MmBackward>)

b. Is there any way to do a matrix operation on `T2` and `T3`? Why or why not?
- No, because you cannot do operations on two tensors where one tensor is 3d and the other is 2d

In [126]:
T0 = T2 + T1
print(T0.grad_fn)

c. The logit function maps numbers between 0 and 1 to $\mathbb{R}$. It is defined $$ logit(x) = \log \left( \frac{x}{1-x} \right) $$
Implement the logit function, and apply it to all values in `T2`

In [82]:
def logit(x):
    numerator = torch.log(x)
    denominator = torch.log(1-x)
    return numerator/denominator
    
logit(T2)

tensor([[   nan,    nan,    nan],
        [0.0941,    nan,    nan],
        [9.8110, 0.0300,    nan],
        [   nan,    nan,    nan],
        [0.9825,    nan, 1.3256]])

Now make an inverse logit function, and apply it to the result of the previous call to show that you have recovered `T2`

In [83]:
def inverse_logit(x):
    numerator = torch.log(x)
    denominator = torch.log(1+x)
    return numerator/denominator
    
inverse_logit(logit(T2))

tensor([[        nan,         nan,         nan],
        [-2.6268e+01,         nan,         nan],
        [ 9.5923e-01, -1.1870e+02,         nan],
        [        nan,         nan,         nan],
        [-2.5814e-02,         nan,  3.3396e-01]])

### 3.3 CUDA Tensors
If you happen to be using a computer with a GPU, you can speed up learning by using CUDA. (As a demonstration. We won't take off points if you don't have a GPU...)

In [87]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

False

## Part 4: Autodifferentiation 
Calculating the derivative of of a function is an essential step in training a neural network. In PyTorch, tensors can be set up to automatically track the derivative every time an operation is performed on them. This is convenient for many different applications in deep learning. Read a more detailed explanation of Autodiff [here](https://pytorch.org/tutorials/beginner/blitz/autograd_tutorial.html#sphx-glr-beginner-blitz-autograd-tutorial-py)

Essentially, if you set the `.requires_grad` attribute when defining a tensor to `True`, all of the operations will be tracked automatically. For example:

In [88]:
tracked_tensor = torch.rand(2,2, requires_grad = True)
print(tracked_tensor)

tensor([[0.3872, 0.3517],
        [0.8268, 0.9008]], requires_grad=True)


In [89]:
sin_tracked_tensor = torch.sin(tracked_tensor)

In [90]:
print(sin_tracked_tensor)

tensor([[0.3776, 0.3445],
        [0.7358, 0.7838]], grad_fn=<SinBackward>)


a. Make 1-D tensors $x$ and $y$, where $y = x^2$, on range of -3 to 3, with 61 points between. Make sure to set `requires_grad` to `True` when you define the `x` tensor!

In [114]:
y = np.random.randint(low = -3, high = 3, size=61).astype("float")
x = y

x = torch.tensor(x, requires_grad=True)
y = torch.tensor(y, requires_grad=True)

Now print `x` and `y` as Numpy arrays. 

In [116]:
# must first 
x.detach().numpy()
y.detach().numpy()

RuntimeError: Can't call numpy() on Variable that requires grad. Use var.detach().numpy() instead.

b. Plot a graph of your function of $y = x^2$

In [ ]:
#### your code here ####

c. Now, take the derviative of $y$ at $x = 1.5$ using PyTorch's autodifferentiation, and save it as `m`.

In [ ]:
#### your code here ####

d. Add the tangent line at $y'(1.5)$ to the original plot of $y = x^2$ (Hint: Remember you can solve $y = mx + b$ for $b$ to find the y-intercept)

In [ ]:
#### your code here ####